Added some checks

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -15,6 +15,22 @@ if ! command -v go &> /dev/null; then
   echo "${prefixString}  \"source /project/go/go_1.13.7/enable\"" ;
   exit 1;
 fi
+if ! command -v clang &> /dev/null ; then
+  echo "${prefixString} ERROR: \"clang\" cannot be found. Please enable a clang/LLVM installation. If you are in Zythos, run the following command:" ;
+  echo "${prefixString}  \"source /project/extra/llvm/9.0.0/enable\"" ;
+  exit 1;
+fi
+tmpFile="`mktemp`" ;
+clang --version &> $tmpFile ;
+grep "clang version" $tmpFile | grep 9.0.0 &> /dev/null ;
+if test $? -ne 0 ; then
+  echo "${prefixString} ERROR: \"clang/LLVM\" installed is version `clang --version | grep 'clang version'`"
+  echo "${prefixString}   You need LLVM 9.0.0 to use NOELLE"
+  echo "${prefixString}   Please read README.md of NOELLE: https://github.com/arcana-lab/noelle/blob/master/README.md";
+  rm $tmpFile ;
+  exit 1;
+fi
+rm $tmpFile ;
 
 # Compile NOELLE
 echo "${prefixString}   Start compiling NOELLE" ;
